version: "3.0"
name: devs

services:

  local_db:
    container_name: local_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - ${MSSQL_ACCESS_PORT}:1433
    environment:
      - MSSQL_SA_PASSWORD_FILE=/run/secrets/local_db_password
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    secrets:
      - local_db_password
    volumes:
      - ${MSSQL_DATA_DIR}:/var/opt/mssql/data
      - ${MSSQL_LOG_DIR}:/var/opt/mssql/logs

secrets:
  local_db_password:
    file: ./secrets/local_db/password.txt