name: CI - Vadalo.Base

on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - Vadalo.Base/**

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Vadalo.Base/Code

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet Packages
        run: dotnet restore
      
      - name: Build
        run: dotnet build

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: Vadalo.Base/Tests

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet Packages
        run: dotnet restore
      
      - name: Unit Tests
        run: dotnet test